

== Containers


=== Small

==== Souffle Cups
For small stuff, consider https://www.amazon.com/gp/product/B075Y2BSS7/[Souffle Cups,window=_blank].
The 3.25oz size is ~quarter cup, the 5.5oz size is ~half cup.
They both use the same lid.

These are great for small portions of flavor-dense condiments, toppings, and sauces.
They are easier to freeze and grab than using the ice cube tray trick.

Additionally, a few souffle cups filled with pre-prepped-and-frozen standard ingredients (like minced garlic or diced onions) can save time.


=== Medium

==== Mason Jars

It's hard to beat mason jars, so long as it can fit (or be coerced) into the opening.
Mason jars come if a variety of volumes: half pint, pint, pint and a half, quart, half gallon, and others.
As for the jar opening, here are "regular," "wide mouth," and some smaller, less-used sizes.

They are ubiquitous, cheap, and easy to replace when inevitably dropped and broken.

Start with wide mouth jars in the quart size - it's a handy and ubiquitous size.
These are available in a number of places, including the grocery store in the "canning supplies" section.

Stick with wide mouth for single-lid-size consistency.
Pints, 1.5 pint, and half-gallon all come in a wide mouth.
These are the most common volumes.
While working with mason jars, a https://www.amazon.com/gp/product/B003FIONES/[funnel,window=_blank] will inevitably be useful.
These mason-jar-specific funnels fit tightly inside the jar rim, so there is little shifting/rebalancing while using.

The "standard" lid for mason jars are the two-piece https://www.amazon.com/dp/B09GYLGHZ2/[lids and bands,window=_blank] and usually come with the jars.
These are used in canning where pressure cooking causes the lid to seal itself against the jar opening.
Canning is its own pursuit.
For room temp or fridge items, consider some way to vacuum out the air for longer 'shelf life.'
There are a number of ways to do this, but battery operated https://www.amazon.com/gp/product/B0DC93DKH5/[jar vacuums,window=_blank] are the most convenient.

There are plenty of other lids in the market, most of them one-piece.
For things on the counter, https://www.amazon.com/gp/product/B09QXY73BY/[wooden lids with silicone seals,window=_blank].
For another aesthetic, https://www.amazon.com/gp/product/B000FKGGZ8/[a stainless version,window=_blank].
For things in the fridge or maybe even freezer, https://www.amazon.com/gp/product/B07Q4ZGW71/[leak-proof,window=_blank] plastic.

Ways to trick out mason jar flow and usage abound.
For example, https://masonjarlifestyle.com/[Mason Jar Lifestyle,window=_blank].
Google for "mason jar accessories" and enjoy many other options.




==== Deli Containers

Deli containers in a variety of sizes can also be useful.
Most glass mason jars are suitable for freezer storage, especially the straight-sided varieties.
However, it only takes a few freezer incidents of jar breaking to send one looking for alternatives.
Losing a quart of homemade stock to jar breaks is a real heartbreaker.

Choose a brand that shares lid sizes.
Cup, pint, and quart of the https://www.amazon.com/gp/product/B06Y6DHN5Z/[EDI brand,window=_blank] all use the same lid.
Proper deli containers are rugged, washable, and reusable.
Lids tend to stain.

NOTE: I have used deli containers for quite some time.
The convenience of sous vide cooking and reheating is pushing me in the vacuum-sealed direction.






=== Large


TODO: rubbermaid consumer and kitchen go here.

