

== Ferments




=== Kefir

Kefir is the cheapest and easiest way to start incorporating a high volume of probiotics into your diet with minimal fuss.
Kefir grains are resilient and can adapt to many different schedules.

I was introduced to https://en.wikipedia.org/wiki/Kefir[kefir,window=_blank] by a friend who used it to
control https://en.wikipedia.org/wiki/Ulcerative_colitis[ulcerative colitis,window=_blank].
There has been plenty written and spoken about kefir.
Health claims abound.

I consume kefir every day -- usually ~pint in the morning with other supplements, sometimes at night if I have more kefir available.
Kefir is a solid foundation for a healthy gut.
I treat it like medicine.


To start a kefir culture:

. Watch a https://youtu.be/94KhDUapXbQ?si=z_xDTOV4Yyuf5WmR&t=580[brief introduction,window=_blank].
. Watch a https://www.youtube.com/watch?v=n_ayUEYZos8[longer and more detailed treatment,window=_blank].
. In both videos, notice the use of jars, strainers, and measuring cups.  This is all the required equipment one will need.
. If you need glassware for incubation, get some quart sized, wide-mouth mason jars.
. If you need a strainer, get a nice https://www.amazon.com/gp/product/B007426KZG/[stainless,window=_blank] or cheap https://www.amazon.com/gp/product/B00RGWGEVO/[nylon,window=_blank] set and strain into a https://www.amazon.com/AmazonCommercial-Glass-Measuring-Capacity-Liters/dp/B08BP61ZY9/[good working sized,window=_blank] vessel with a pour spout.
. Get some kefir grains from a friend or https://www.fusionteas.com/fresh-milk-kefir-grains[mail order,window=_blank].

In my current location, I have ready access to https://en.wikipedia.org/wiki/Raw_milk[raw milk,window=_blank].
I like raw milk for a number of reasons and it makes fantastic kefir.
If I *didn't* have ready access to raw milk, I would still make kefir with grocery market cow milk.


Over time, the beasties will replicate and the grains will grow.
Periodically, trim the grains used in incubations.
They can be shared with friends, included in other dishes, or just eaten as-is.

Kefir is resilient and the making of it is mostly hands-off.
After a few repetitions, you will find the fermentation speed that works for you.
The variables are amount of grains, the amount of milk, and the temperature at which it incubates.
For example, I produce one quart of kefir on a regular schedule.
To accomplish this, I keep my mass of grains to around 40grams.
I don't weight this every day, I trim to this about once a week.
This allows me to take one quart of cold milk out of the fridge, mix with grains, and expect a full fermentation in 24h.

Don't get too wrapped up in precision.
This is medicine, not amuse bouche.






=== Yogurt

Yogurt is almost as easy to produce as kefir.
Yogurt making *does* require more equipment, but there are choices.
The basic protocol is similar to kefir, but with an emphasis on longer incubation at higher-than-room-temperatures.


Prerequisites and preparation:

. Watch a crash course on https://www.youtube.com/watch?v=fqvouttKjZ0[yogurt making].  The big algorithm in the sky will recommend others as well.
. Choose a method for maintaining a moderate (~100F) temperature.
. Choose a starter culture.
. Choose a dairy.
. Consider a prebiotic (food for the beasties).


On temperature maintenance, there are options.

The oven method, highlighted in the crash course video, can be done by anyone with an oven.
I find this method fussy and difficult to predict.
If you have the availability, or perhaps even enjoy 
I like the ability to set a specific time and expect a result in a time frame that is reasonably predictable.

If you have a multicooker



