

== Ferments




=== Kefir

Kefir is the cheapest and easiest way to start incorporating a high volume of probiotics into your diet with minimal fuss.
Kefir grains are resilient and can adapt to many different schedules.

I was introduced to https://en.wikipedia.org/wiki/Kefir[kefir,window=_blank] by a friend who used it to
control https://en.wikipedia.org/wiki/Ulcerative_colitis[ulcerative colitis,window=_blank].
There has been plenty written and spoken about kefir.
Health claims abound.

I consume kefir every day -- usually ~pint in the morning with other supplements, sometimes at night if I have more kefir available.
Kefir is a solid foundation for a healthy gut.
I treat it like medicine.


To start a kefir culture:

. Watch a https://youtu.be/94KhDUapXbQ?si=z_xDTOV4Yyuf5WmR&t=580[brief introduction,window=_blank].
. Watch a https://www.youtube.com/watch?v=n_ayUEYZos8[longer and more detailed treatment,window=_blank].
. In both videos, notice the use of jars, strainers, and measuring cups.  This is all the required equipment one will need.
. If you need glassware for incubation, get some quart sized, wide-mouth mason jars.
. If you need a strainer, get a nice https://www.amazon.com/gp/product/B007426KZG/[stainless,window=_blank] or cheap https://www.amazon.com/gp/product/B00RGWGEVO/[nylon,window=_blank] set and strain into a https://www.amazon.com/AmazonCommercial-Glass-Measuring-Capacity-Liters/dp/B08BP61ZY9/[good working sized,window=_blank] vessel with a pour spout.
. Get some kefir grains from a friend or https://www.fusionteas.com/fresh-milk-kefir-grains[mail order,window=_blank].

In my current location, I have ready access to https://en.wikipedia.org/wiki/Raw_milk[raw milk,window=_blank].
I like raw milk for a number of reasons and it makes fantastic kefir.
If I *didn't* have ready access to raw milk, I would still make kefir with grocery market cow milk.


Over time, the beasties will replicate and the grains will grow.
Periodically, trim the grains used in incubations.
They can be shared with friends, included in other dishes, or just eaten as-is.

Kefir is resilient and the making of it is mostly hands-off.
After a few repetitions, you will find the fermentation speed that works for you.
The variables are amount of grains, the amount of milk, and the temperature at which it incubates.
For example, I produce one quart of kefir on a regular schedule.
To accomplish this, I keep my mass of grains to around 40grams.
I don't weight this every day, I trim to this about once a week.
This allows me to take one quart of cold milk out of the fridge, mix with grains, and expect a full fermentation in 24h.

Don't get too wrapped up in precision.
This is medicine, not amuse bouche.






=== Yogurt

Yogurt is almost as easy to produce as kefir.
Yogurt making *can* require more equipment, and there are choices.
The basic protocol is similar to kefir, but with an emphasis on longer incubation at higher-than-room-temperatures.


Prerequisites and preparation:

. Watch a crash course on https://www.youtube.com/watch?v=fqvouttKjZ0[yogurt making].  The big algorithm in the sky will recommend others as well.
. Choose a method for maintaining a moderate (~100F) temperature.  See below.
. Choose a starter culture. I typically make a specific batch with cultures not seen in over-the-counter yogurt (like https://cuttingedgecultures.com/our-blog/l-reuteri-and-l-gasseri-superfoods-are-all-about-bacterial-counts/[L. Reuteri and L. Gasseri].  However, if you have a supermaket brand you like, and it's got live and active cultures in it, you can use it to make your own.
. Choose a dairy. I use half-an-half most often because I like the thick and fatty consistency.
. Consider a prebiotic (food for the beasties). The most cost effective food I've used is https://www.amazon.com/dp/B074WKCPS4[inulin powder].


On temperature maintenance, there are options:

The oven method, highlighted in the crash course video, can be done by anyone with an oven.
I find this method fussy and difficult to predict.
If you have the availability, or perhaps even enjoy the unpredictability, this is the method for you.
I like the ability to set a specific time and expect a result in a time frame that is reasonably predictable.

If you have a multicooker (e.g.: Instant Pot), you can include https://www.youtube.com/watch?v=U_vejmAr-Ac[all ingredients and click go].

If you have a sous vide circulator, you get to choose any size container you want.
This https://www.youtube.com/watch?v=PMInAL7JRRo[short video] from ChefsSteps is a good place to start.
Juat a few years ago, sous vide circulators were very expensive (> 1k).
These days, you can get one for less than a hundred dollars.

Browsing other videos is recommended while you get a feel for yogurt making.
There are many varieties on time, temp, additional ingredients, etc.


My go-to workup is:

. One quart of half-and-half
. Two tablespoons culture (specific or mixture from a commercial brand)
. Two tablespoons inulin powder
. Sous vide at 100F for 24-36 hours in mason jars

I have not been convinced on the need to boil first.
I do, however, insist that the culture and inulin powder are well-incorporated before sealing jars.
The inulin powder, in particular, clumps on me when put into warm half and half.

I make multiple quarts at a time, starting with a large vessel of dairy to mix all ingredients,
then separating into pint or quart jars for the incubation.
I whisk the inulin and starter culter vigorously in a smaller amount of dairy before incorporating.

It is not out of the ordinary for the first incubation to produce grainy or separated results.
It still tastes fine: you can just blend it back together or pour off the whey.
When this happens, the next batch is usually thick and creamy.


