




== Pork

=== Introduction

At the time of this writing (~2025), beef prices are nuts.
This has increased my interest in pork.




=== Cured


==== Bacon

I dry cure pork belly, smoke it, and enjoy it.
There isn't much too it, this https://www.youtube.com/watch?v=mkAEYrgvVUk[short video from Joshua Weismann] is a fine place to start.

I make a big batch of bacon cure:

* 400g kosher
* 200g sugar
* 60g prague powder 1

and use 2.5% on pork belly by weight.

I dry cure these under vacuum for 7d.
After 7d, rinse, dry, and let pellicle up in the fridge.
Smoke and enjoy.



==== Ham

Start with a green pig leg.
If you get a manageable sized leg from your butcher, you're letting the market work for you!

If you get a whole 'green ham' or 'raw' pig leg, you have some choices.
The first one of these I did, i simply wet cured the whole thing.
This made it a bit unwieldy to carve up since you're starting with ~25lb leg.
These days, I break them down once thawed out.
This https://www.youtube.com/watch?v=fEWFbdOCZMY[Video from Food Farmer Earth] is a good one.
There are plenty others.

I find it easier to dry cure.

Big batch of ham cure:

* 600g salt
* 300g sugar
* 50g  prague 1

and use 5% on pork by weight.

I dry cure these under vacuum for 7d.
After 7d, rinse, dry, and let pellicle up in the fridge.
Smoke and enjoy.

I've trid wet curing ham - it was fine.
Dry curing is less mess and still makes great ham.

